defaults:
  - maze

map: |-
  [
    [1, 1, 1, 1,   1, 1, 1,   1,   1, 1, 1, 1, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, R:A, 0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, R:O, 0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 0, 0, 0,   0, 0, 0,   0,   0, 0, 0, 0, 1],
    [1, 1, 1, 1,   1, 1, 1,   1,   1, 1, 1, 1, 1],
  ]

agent_id_map:
  A: [agent]
  O: [goal0]

scale: 2.0
floor_texture: checker
floor_texrepeat: [10, 10]
