defaults:
  - maze

map: |-
  [
    [0,   0,   0,   0,   0,   0,   0,   0, 0],
    [0,   R,   R,   R,   R,   R,   R,   R, 0],
    [0,   R,   0,   0,   0,   0,   0,   R, 0],
    [0,   R, R:O, R:O, R:O, R:O, R:O,   R, 0],
    [0,   R, R:O, R:O,   R, R:O, R:O,   R, 0],
    [0,   R, R:O, R:O, R:O, R:O, R:O,   R, 0],
    [0,   R, R:O, R:O,   R, R:O, R:O,   R, 0],
    [0,   R, R:O, R:O, R:O, R:O, R:O,   R, 0],
    [0,   R,   0,   0,   0,   0,   0,   R, 0],
    [0,   R,   R,   R,   R,   R,   R,   R, 0],
    [0,   0,   0,   0,   0,   0,   0,   0, 0],
  ]

agent_id_map:
  O: ${oc.dict.keys:env.agents}

scale: 2.0
