defaults:
  - combined

features_extractor_kwargs:
  image_extractor:
    _target_: cambrian.ml.features_extractors.MjCambrianSpatialCNNExtractor
    _partial_: true
    features_dim: 32
    activation:
      _target_: torch.nn.ReLU
      _partial_: true
    channels: [8, 16, 32]
    kernel_sizes: [5, 3, 3]
    strides: [2, 1, 1]
    hidden_dim: 64

net_arch:
  pi: [64, 64]
  vf: [64, 64]
